In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import os
from scipy.io import wavfile
from collections import defaultdict, Counter
from scipy import signal
import numpy as np
import librosa
import random as rn
from keras import Input
#from keras.engine import Model
from keras.layers import Dense, TimeDistributed, Dropout, Bidirectional, GRU, BatchNormalization, Activation, LeakyReLU, LSTM, Flatten, RepeatVector, Permute, Multiply, Conv2D, MaxPooling2D
import librosa
import pandas as pd
from PIL import Image
import pathlib
import csv 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import keras
from keras import layers

In [1]:
import soundfile as sf
sf.available_subtypes('WAV')

{'PCM_16': 'Signed 16 bit PCM',
 'PCM_24': 'Signed 24 bit PCM',
 'PCM_32': 'Signed 32 bit PCM',
 'PCM_U8': 'Unsigned 8 bit PCM',
 'FLOAT': '32 bit float',
 'DOUBLE': '64 bit float',
 'ULAW': 'U-Law',
 'ALAW': 'A-Law',
 'IMA_ADPCM': 'IMA ADPCM',
 'MS_ADPCM': 'Microsoft ADPCM',
 'GSM610': 'GSM 6.10',
 'G721_32': '32kbs G721 ADPCM'}

In [2]:
import tensorflow as tf
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [ ]:
# prepare known data
volume_path = 'C:/Users/USER/Desktop/part2_full_train_4X5000'

FilePathList = []
labels = []
for dirName, subdirList, fileList in os.walk(volume_path):
    for filename in fileList:
        if '.csv' not in filename:
            FilePathList.append(volume_path + '/' + filename)
            labels.append(int(filename[0]))
        else:
            pd_label = pd.read_csv(volume_path + '/' + filename)

labels = np.array(labels)
print(labels.shape)

In [ ]:
sampling_rate = 16000   # 1초에 16000번
n_mels = 64

In [ ]:
##train set
y_labels_aug = []
X_mel_aug1 = []
X_mel_aug2 = []
file_split_num_train = []
for i, filepath in enumerate(X_train_path):
    y, sr = librosa.load(filepath, mono=True, sr=sampling_rate)
    index_f = 0
    for j in range(y.size //(sampling_rate//2)):
        X_aug_seg = y[index_f:index_f + (sampling_rate//2)]
        
        S = librosa.feature.melspectrogram(y=X_aug_seg, sr=sampling_rate, n_mels=n_mels, fmax=8000)
        S_dB = librosa.power_to_db(S, ref=np.max)
        X_mel_aug1.append(S_dB)
        
        y_labels_aug.append(y_train_raw[i])
        index_f = index_f + (sampling_rate//2)
    file_split_num_train.append(j + 1)
    
X_train1 = np.array(X_mel_aug1)
y_train1 = np.array(y_labels_aug)
print('train set.shape : ', X_train1.shape)
print('train set.shape : ', y_train1.shape)

In [37]:
import matplotlib.pyplot as plt
import librosa.display
### wav 파일 스펙토그램 png 파일로 변환 후 저장하기
#for filename in os.listdir(f'/content/drive/MyDrive/Dataset/audiofile_shorted500'):
audioname = 'C:/Users/USER/Desktop/INR_음성/all_mono.wav'
y, sr = librosa.load(audioname, mono=True, duration=10)

In [65]:
y.shape

(220500,)

In [39]:
fig, ax = plt.subplots()
S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128, fmax=8000)
S_dB = librosa.power_to_db(S, ref=np.max)
librosa.display.specshow(S_dB, sr=sr, fmax=8000, ax=ax)
#plt.specgram(y, NFFT=2048, Fs=16000, Fc=0, noverlap=128, sides='default', mode='default', scale='dB');
plt.axis('off');
plt.savefig('C:/Users/USER/Desktop/sample.png')
plt.clf()

# im =Image.fromarray(S).convert('F') 
# im.show()
# im.save('C:/Users/USER/Desktop/sample2.png')

<Figure size 432x288 with 0 Axes>

In [52]:
#from tiff to wav 
import matplotlib.pyplot as plt

im = plt.imread('C:/Users/USER/Desktop/sample.png')
#im=Image.open('C:/Users/USER/Desktop/sample.png') 
import numpy as np
img = np.array(im)
# pil_image=Image.fromarray(img)
# pil_image.show()

In [47]:
type(pil_image)

PIL.Image.Image

In [53]:
img.shape

(288, 432, 4)

In [63]:
wav.shape

(288, 1536)

In [66]:
S = librosa.feature.inverse.mel_to_stft(img)
y = librosa.griffinlim(S)
import soundfile
soundfile.write("10.wav", y, samplerate=sr)

RuntimeError: Error opening '10.wav': Format not recognised.

In [30]:
#from tiff to wav 
im=Image.open('C:/Users/USER/Desktop/sample.tiff') 
import numpy as np
img=np.array(im)
print(img)

[[[ 1  0  0]
  [ 1  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [10 13 13]
  [ 0  2  5]]

 [[ 3  3  1]
  [ 2  1  2]
  [ 0  0  0]
  ...
  [ 1  1  0]
  [ 8  7 10]
  [ 5  5 10]]

 [[ 5  7  5]
  [ 3  4  5]
  [ 0  0  0]
  ...
  [ 6  4  5]
  [ 9 12 17]
  [ 3  5  9]]

 ...

 [[ 0  0  0]
  [ 4  7  3]
  [ 3  4  3]
  ...
  [ 0  0  0]
  [ 1  4  6]
  [ 0  1  0]]

 [[ 2  2  0]
  [ 3  5  3]
  [ 8  8 10]
  ...
  [ 0  3  4]
  [ 6  8  7]
  [ 0  4  0]]

 [[ 9  4  3]
  [ 0  0  1]
  [ 8  7 10]
  ...
  [ 0  4  4]
  [ 0  3  0]
  [ 0  1  0]]]


In [33]:
wav=librosa.feature.inverse.mel_to_audio(img)
print(img)
import soundfile
soundfile.write("reconstruction.wav",wav,samplerate=sr)

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'